version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finances
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
  app:
    build:
      context: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=finances
      - SECRET_KEY=14a7ccc14caec5c362a1d272dded9a3b9f7a85fcb005a8f8c3f49c8814be6b7c
      - spring_profiles_active=dev
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
